//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]



[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_automatonnumber")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
public partial class new_automatonnumber : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{

	public new_automatonnumber() :
			base(EntityLogicalName)
	{
	}

	public const string EntityLogicalName = "new_automatonnumber";

	public const string EntityLogicalCollectionName = "new_automatonnumbers";

	public const string EntitySetName = "new_automatonnumbers";

	public const int EntityTypeCode = 10707;

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}

	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_automatonnumberid")]
	public System.Nullable<System.Guid> new_automatonnumberId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_automatonnumberid");
		}
		set
		{
			this.OnPropertyChanging("new_automatonnumberId");
			this.SetAttributeValue("new_automatonnumberid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("new_automatonnumberId");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_automatonnumberid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.new_automatonnumberId = value;
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_currentnumber")]
	public System.Nullable<int> new_currentnumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_currentnumber");
		}
		set
		{
			this.OnPropertyChanging("new_currentnumber");
			this.SetAttributeValue("new_currentnumber", value);
			this.OnPropertyChanged("new_currentnumber");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_entityname")]
	public string new_entityname
	{
		get
		{
			return this.GetAttributeValue<string>("new_entityname");
		}
		set
		{
			this.OnPropertyChanging("new_entityname");
			this.SetAttributeValue("new_entityname", value);
			this.OnPropertyChanged("new_entityname");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_fieldname")]
	public string new_fieldname
	{
		get
		{
			return this.GetAttributeValue<string>("new_fieldname");
		}
		set
		{
			this.OnPropertyChanging("new_fieldname");
			this.SetAttributeValue("new_fieldname", value);
			this.OnPropertyChanged("new_fieldname");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_numberid")]
	public string new_numberid
	{
		get
		{
			return this.GetAttributeValue<string>("new_numberid");
		}
		set
		{
			this.OnPropertyChanging("new_numberid");
			this.SetAttributeValue("new_numberid", value);
			this.OnPropertyChanged("new_numberid");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public System.Nullable<OptionSets.statecode> statecode
	{
		get
		{
			Microsoft.Xrm.Sdk.OptionSetValue attributeValue = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
			if ((attributeValue != null))
			{
				return ((OptionSets.statecode)(System.Enum.ToObject(typeof(OptionSets.statecode), attributeValue.Value)));
			}
			else
			{
				return null;
			}
		}
		set
		{
			this.OnPropertyChanging("statecode");
			if ((value == null))
			{
				this.SetAttributeValue("statecode", value);
			}
			else
			{
				this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
			}
			this.OnPropertyChanged("statecode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue statuscode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value);
			this.OnPropertyChanged("statuscode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}

	public sealed class OptionSets
	{

		[System.Runtime.Serialization.DataContractAttribute()]
		[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
		public enum statecode
		{

			[System.Runtime.Serialization.EnumMemberAttribute()]
			Active = 0,

			[System.Runtime.Serialization.EnumMemberAttribute()]
			Inactive = 1,
		}
	}
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_case")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
public partial class new_case : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{

	public new_case() :
			base(EntityLogicalName)
	{
	}

	public const string EntityLogicalName = "new_case";

	public const string EntityLogicalCollectionName = "new_cases";

	public const string EntitySetName = "new_cases";

	public const int EntityTypeCode = 10706;

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}

	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_caseid")]
	public System.Nullable<System.Guid> new_caseId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_caseid");
		}
		set
		{
			this.OnPropertyChanging("new_caseId");
			this.SetAttributeValue("new_caseid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("new_caseId");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_caseid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.new_caseId = value;
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_casenumber")]
	public string new_casenumber
	{
		get
		{
			return this.GetAttributeValue<string>("new_casenumber");
		}
		set
		{
			this.OnPropertyChanging("new_casenumber");
			this.SetAttributeValue("new_casenumber", value);
			this.OnPropertyChanged("new_casenumber");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_customer")]
	public Microsoft.Xrm.Sdk.EntityReference new_customer
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_customer");
		}
		set
		{
			this.OnPropertyChanging("new_customer");
			this.SetAttributeValue("new_customer", value);
			this.OnPropertyChanged("new_customer");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_description")]
	public string new_description
	{
		get
		{
			return this.GetAttributeValue<string>("new_description");
		}
		set
		{
			this.OnPropertyChanging("new_description");
			this.SetAttributeValue("new_description", value);
			this.OnPropertyChanged("new_description");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_enddatesla")]
	public System.Nullable<System.DateTime> new_enddatesla
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_enddatesla");
		}
		set
		{
			this.OnPropertyChanging("new_enddatesla");
			this.SetAttributeValue("new_enddatesla", value);
			this.OnPropertyChanged("new_enddatesla");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_endsla")]
	public System.Nullable<System.DateTime> new_endsla
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("new_endsla");
		}
		set
		{
			this.OnPropertyChanging("new_endsla");
			this.SetAttributeValue("new_endsla", value);
			this.OnPropertyChanged("new_endsla");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_newtopic")]
	public Microsoft.Xrm.Sdk.EntityReference new_newtopic
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_newtopic");
		}
		set
		{
			this.OnPropertyChanging("new_newtopic");
			this.SetAttributeValue("new_newtopic", value);
			this.OnPropertyChanged("new_newtopic");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_slaexceeded")]
	public System.Nullable<bool> new_slaexceeded
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("new_slaexceeded");
		}
		set
		{
			this.OnPropertyChanging("new_slaexceeded");
			this.SetAttributeValue("new_slaexceeded", value);
			this.OnPropertyChanged("new_slaexceeded");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_status")]
	public Microsoft.Xrm.Sdk.OptionSetValue new_status
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("new_status");
		}
		set
		{
			this.OnPropertyChanging("new_status");
			this.SetAttributeValue("new_status", value);
			this.OnPropertyChanged("new_status");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_treatmentdescription")]
	public string new_treatmentdescription
	{
		get
		{
			return this.GetAttributeValue<string>("new_treatmentdescription");
		}
		set
		{
			this.OnPropertyChanging("new_treatmentdescription");
			this.SetAttributeValue("new_treatmentdescription", value);
			this.OnPropertyChanged("new_treatmentdescription");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public System.Nullable<OptionSets.statecode> statecode
	{
		get
		{
			Microsoft.Xrm.Sdk.OptionSetValue attributeValue = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
			if ((attributeValue != null))
			{
				return ((OptionSets.statecode)(System.Enum.ToObject(typeof(OptionSets.statecode), attributeValue.Value)));
			}
			else
			{
				return null;
			}
		}
		set
		{
			this.OnPropertyChanging("statecode");
			if ((value == null))
			{
				this.SetAttributeValue("statecode", value);
			}
			else
			{
				this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
			}
			this.OnPropertyChanged("statecode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue statuscode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value);
			this.OnPropertyChanged("statuscode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}

	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_case_new_treatmentline_newcase")]
	public System.Collections.Generic.IEnumerable<new_treatmentline> new_new_case_new_treatmentline_newcase
	{
		get
		{
			return this.GetRelatedEntities<new_treatmentline>("new_new_case_new_treatmentline_newcase", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_case_new_treatmentline_newcase");
			this.SetRelatedEntities<new_treatmentline>("new_new_case_new_treatmentline_newcase", null, value);
			this.OnPropertyChanged("new_new_case_new_treatmentline_newcase");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_newtopic")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_topic_new_case_newtopic")]
	public new_topic new_new_topic_new_case_newtopic
	{
		get
		{
			return this.GetRelatedEntity<new_topic>("new_new_topic_new_case_newtopic", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_topic_new_case_newtopic");
			this.SetRelatedEntity<new_topic>("new_new_topic_new_case_newtopic", null, value);
			this.OnPropertyChanged("new_new_topic_new_case_newtopic");
		}
	}

	public sealed class OptionSets
	{

		[System.Runtime.Serialization.DataContractAttribute()]
		[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
		public enum statecode
		{

			[System.Runtime.Serialization.EnumMemberAttribute()]
			Active = 0,

			[System.Runtime.Serialization.EnumMemberAttribute()]
			Inactive = 1,
		}
	}
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_topic")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
public partial class new_topic : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{

	public new_topic() :
			base(EntityLogicalName)
	{
	}

	public const string EntityLogicalName = "new_topic";

	public const string EntityLogicalCollectionName = "new_topics";

	public const string EntitySetName = "new_topics";

	public const int EntityTypeCode = 10705;

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}

	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_name")]
	public string new_name
	{
		get
		{
			return this.GetAttributeValue<string>("new_name");
		}
		set
		{
			this.OnPropertyChanging("new_name");
			this.SetAttributeValue("new_name", value);
			this.OnPropertyChanged("new_name");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_sla")]
	public System.Nullable<int> new_sla
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("new_sla");
		}
		set
		{
			this.OnPropertyChanging("new_sla");
			this.SetAttributeValue("new_sla", value);
			this.OnPropertyChanged("new_sla");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_topicid")]
	public System.Nullable<System.Guid> new_topicId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_topicid");
		}
		set
		{
			this.OnPropertyChanging("new_topicId");
			this.SetAttributeValue("new_topicid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("new_topicId");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_topicid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.new_topicId = value;
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public System.Nullable<OptionSets.statecode> statecode
	{
		get
		{
			Microsoft.Xrm.Sdk.OptionSetValue attributeValue = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
			if ((attributeValue != null))
			{
				return ((OptionSets.statecode)(System.Enum.ToObject(typeof(OptionSets.statecode), attributeValue.Value)));
			}
			else
			{
				return null;
			}
		}
		set
		{
			this.OnPropertyChanging("statecode");
			if ((value == null))
			{
				this.SetAttributeValue("statecode", value);
			}
			else
			{
				this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
			}
			this.OnPropertyChanged("statecode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue statuscode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value);
			this.OnPropertyChanged("statuscode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}

	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_topic_new_case_newtopic")]
	public System.Collections.Generic.IEnumerable<new_case> new_new_topic_new_case_newtopic
	{
		get
		{
			return this.GetRelatedEntities<new_case>("new_new_topic_new_case_newtopic", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_topic_new_case_newtopic");
			this.SetRelatedEntities<new_case>("new_new_topic_new_case_newtopic", null, value);
			this.OnPropertyChanged("new_new_topic_new_case_newtopic");
		}
	}

	public sealed class OptionSets
	{

		[System.Runtime.Serialization.DataContractAttribute()]
		[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
		public enum statecode
		{

			[System.Runtime.Serialization.EnumMemberAttribute()]
			Active = 0,

			[System.Runtime.Serialization.EnumMemberAttribute()]
			Inactive = 1,
		}
	}
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("new_treatmentline")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
public partial class new_treatmentline : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{

	public new_treatmentline() :
			base(EntityLogicalName)
	{
	}

	public const string EntityLogicalName = "new_treatmentline";

	public const string EntityLogicalCollectionName = "new_treatmentlines";

	public const string EntitySetName = "new_treatmentlines";

	public const int EntityTypeCode = 10708;

	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}

	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_linedescription")]
	public string new_linedescription
	{
		get
		{
			return this.GetAttributeValue<string>("new_linedescription");
		}
		set
		{
			this.OnPropertyChanging("new_linedescription");
			this.SetAttributeValue("new_linedescription", value);
			this.OnPropertyChanged("new_linedescription");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_linestatus")]
	public Microsoft.Xrm.Sdk.OptionSetValue new_linestatus
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("new_linestatus");
		}
		set
		{
			this.OnPropertyChanging("new_linestatus");
			this.SetAttributeValue("new_linestatus", value);
			this.OnPropertyChanged("new_linestatus");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_newcase")]
	public Microsoft.Xrm.Sdk.EntityReference new_newcase
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("new_newcase");
		}
		set
		{
			this.OnPropertyChanging("new_newcase");
			this.SetAttributeValue("new_newcase", value);
			this.OnPropertyChanged("new_newcase");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_treatmentlineid")]
	public System.Nullable<System.Guid> new_treatmentlineId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("new_treatmentlineid");
		}
		set
		{
			this.OnPropertyChanging("new_treatmentlineId");
			this.SetAttributeValue("new_treatmentlineid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("new_treatmentlineId");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_treatmentlineid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.new_treatmentlineId = value;
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public System.Nullable<OptionSets.statecode> statecode
	{
		get
		{
			Microsoft.Xrm.Sdk.OptionSetValue attributeValue = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
			if ((attributeValue != null))
			{
				return ((OptionSets.statecode)(System.Enum.ToObject(typeof(OptionSets.statecode), attributeValue.Value)));
			}
			else
			{
				return null;
			}
		}
		set
		{
			this.OnPropertyChanging("statecode");
			if ((value == null))
			{
				this.SetAttributeValue("statecode", value);
			}
			else
			{
				this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
			}
			this.OnPropertyChanged("statecode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public Microsoft.Xrm.Sdk.OptionSetValue statuscode
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value);
			this.OnPropertyChanged("statuscode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}

	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("new_newcase")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("new_new_case_new_treatmentline_newcase")]
	public new_case new_new_case_new_treatmentline_newcase
	{
		get
		{
			return this.GetRelatedEntity<new_case>("new_new_case_new_treatmentline_newcase", null);
		}
		set
		{
			this.OnPropertyChanging("new_new_case_new_treatmentline_newcase");
			this.SetRelatedEntity<new_case>("new_new_case_new_treatmentline_newcase", null, value);
			this.OnPropertyChanged("new_new_case_new_treatmentline_newcase");
		}
	}

	public sealed class OptionSets
	{

		[System.Runtime.Serialization.DataContractAttribute()]
		[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.82")]
		public enum statecode
		{

			[System.Runtime.Serialization.EnumMemberAttribute()]
			Active = 0,

			[System.Runtime.Serialization.EnumMemberAttribute()]
			Inactive = 1,
		}
	}
}

